fix(fixed the majority of todos): fixed todos and added some type def…
Entermedia-LLC/nextjs-starter pull request #6
Opened 2023-01-23 19:49 UTC by Danishkhurshid

…initions

2023-01-23 20:33 UTC, bmarshall511 requested changes
@Danishkhurshid Looks great! Just a handful of things & then we can get it merged.

2023-01-23 20:33 UTC, bmarshall511 commented on types/wordpress/menus.d.ts
> +  target?: "_self" | "_blank" | undefined;
@Danishkhurshid This shouldn't be limited, targets can be any kind of string.

2023-01-23 20:33 UTC, bmarshall511 commented on types/wordpress/blocks.d.ts
> +    htmlType?: "submit"| "button" | "reset";
@Danishkhurshid This shouldn't be limited, can potentially be one of many different types that HTML provides for different elements

2023-01-23 20:33 UTC, bmarshall511 commented on functions/wordpress/postTypes/getPostTypeStaticPaths.ts
> +    .filter((post: any) =>
@Danishkhurshid Please add a TODO above this line

2023-01-23 20:33 UTC, bmarshall511 commented on functions/wordpress/postTypes/getPostTypeStaticPaths.ts
> +    .map((post: any) => {
@Danishkhurshid Please move the @TODO comment above to the line above here. Ideally, there should be a @TODO for each instance of an issue for better tracking

2023-01-23 20:33 UTC, bmarshall511 commented on app/components/atomic-design/molecules/Navigation/Navigation.tsx
> +  target?: "_blank" | "_self" | undefined;
@Danishkhurshid This shouldn't be limited, can be any string

2023-01-23 20:33 UTC, bmarshall511 commented on app/components/atomic-design/molecules/Navigation/Navigation.tsx
> +            {item?.children?.items && (
@Danishkhurshid If any empty array was provided, wouldn't this still get triggered (which we don't want to happen)?

2023-01-27 15:20 UTC, bmarshall511 commented
@Danishkhurshid Please address the items we spoke about:

1. Look into import the Gutenberg block props from Gutenberg into our blocks definition vs. adding it in individual files
2. Get your local setup & test thoroughly. Using the nextstarter, once you have WP installed and setup, you should be able to go to /wordpress to see the homepage.
3. Finish the work you're currently doing for the component styles
4. Look into how to reuse the scoped component styles vs. adding it to every defined component

2023-01-30 13:33 UTC, bmarshall511 requested changes

2023-01-30 13:33 UTC, bmarshall511 commented on types/wordpress/blocks.d.ts
> +    htmlType?: ButtonProps.htmlType;
@Danishkhurshid Needs to be a string as mentioned before, shouldn't be Ant specific

2023-01-30 13:33 UTC, bmarshall511 commented on app/wordpress/[slug]/page.tsx
> +
@Danishkhurshid Did you look into moving this under the block types we've defined as discussed?

2023-01-30 13:37 UTC, Danishkhurshid commented on app/wordpress/[slug]/page.tsx
> +
@bmarshall511 yes. Need to implicitly add a type here.

2023-01-30 13:37 UTC, Danishkhurshid commented on types/wordpress/blocks.d.ts
> +    htmlType?: ButtonProps.htmlType;
@bmarshall511 this file no longer exists.

2023-01-30 13:56 UTC, merged